[build-system]
requires = ["scikit-build-core", "setuptools", "wheel", "pybind11-stubgen"]
build-backend = "scikit_build_core.build"

[project]
name = "mathInterval"
version = "0.1.0"
requires-python = ">=3.8"
