name: generate pybind11_stubgen
on:
  workflow_dispatch:
jobs:
  pybind11_stubgen:
    name: Build pybind11 stubgen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install pybind11_stubgen
        run: python -m pip install pybind11_stubgen

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: generate stubgen
        run: |
          pybind11-stubgen mathInterval
        env:
          PYTHONPATH: $PYTHONPATH:.

      - name: Upload wheels (GitHub Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: mathInterval.pyi
          path: stubs/mathInterval.pyi
